# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jens Jørgensen
#title: Senior Network System Administrator
email: hello@jensu.dk
phone: +45 2o669649
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  jensuj
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: jensuj
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: 
#  icon: fas fa-globe
#  url: 
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jens and I'm an architect working in computation, simulation and data...

  I am currently interested in: <mark>Neo4j</mark>
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        border: weak
        title: 3XN/GXN & CITA
        sub_title: Industrial PhD Researcher
        caption: apr. 2020 - apr. 2022
        link: www.3xn.dk
        quote: >
          Research and Development of technologies for conducting occupancy surveys and analysis,, using computer vision and graph databases.
        description: | # this will include new lines to allow paragraphs
          **About:** As industrial PhD researcher, I developed a framework for collecting and analysing data on how the built environment is used.
          The projects focus was to get as much information about how architecture is used, back to the architects who plan and design it.

          - Mapping of existing technologies and methods, in relation to company interests.
          - Development of prototype, capable of detecting objects and and their semantic relationships
          - Development of graph database in Neo4j for storage and analysis of query results.
          - Internal consultancy, on data driven design and use of sensors.

          **Tools and Technologies:** Nvidia Jetson, Kinect Azure, Xovis, Ubiqisense, Neo4j + Dash & Bloom, Rhino3D, Grasshopper, PyTorch Python, Pandas, Docker, VS devcontainer, Pedsim Pro

      - layout: left
        border: weak
        title: 3XN/GXN
        sub_title: Computational Architecht
        caption: sep. 2019 - apr. 2020
        link: www.3xn.dk
        quote: >
          GXN is a research and development consultancy, working with behavior and sustainability in the built environment. They function as RnD for 3XN Architects.
        description: | # this will include new lines to allow paragraphs
          **About:** 
          -   Supporting design processes with daylight, climate and pedestrian simulations.
          -   Developing prototype for building sensor network and dashboards.

          **Tools and Technologies:** Rhino3D, Grasshopper, Climate-Studio, Diva, Ladybug/Honeybee, PedSim Pro, Pycom, Influx Data, Grafana   

      - layout: left
        border: weak
        title: Diffus Design
        sub_title: Developer
        caption: mar. 2016 - jun. 2017
        link: www.diffus.dk
        quote: >
          Diffus Design creates products and projects based on sensor technology merged with traditional materials and craft, with a focus on intelligent textiles, wearable technology.
        description: | # this will include new lines to allow paragraphs
          **About:** At Diffus Design I worked as a prototype builder, helping the design company realize their designs and ideas. 
          Working together with cutting edge industrial R&D and academic researchers alike, the prototypes involved integrating multiple technologies, materials and design paradigms.

          - Control and dimming development for [ELAC (Embroidered Light for Acoustic Ceilings)](https://diffus.dk/work/project-elac/) prototype.
          - Development of sensing, led-drivers and lighting response for [Light.Touch.Matters](https://diffus.dk/work/project-light-touch-matters/) prototype.
          - Development of sensing and lighting response for [CREATIF](https://diffus.dk/work/project-creatif/) prototype.

          **Tools and Technologies:** Arduino, Teensy, VS Code, PlatformIO, Python, Rhino3D, Grasshopper, Adobe CS 

      - layout: left
        border: weak
        title: Dark Matters
        sub_title: Design and Development
        caption: mar. 2015 - mar. 2016
        link: www.darkmatters.dk
        quote: >
          Dark Matters is a interdesciplinary design studio. Creating instalations, motion graphics and lighting design, they operate at the intersection of architecture, scenography, design and art.
        description: | # this will include new lines to allow paragraphs
          **About:** At Dark Matters I conceptualized, designed and produced visuals, lighting design and instalaltions for concerts and cultural events.
          I would be resposible for planning and executing technical installations, often one-offs and on a tight budget and timeplan.

          - Production Design and Touring of Den Sorte Skole [Indians & Cowboys A/V Tour](https://densorteskole.net/avprojects/Indians%20&%20Cowboys)
          - Concept, Development and Production of [Blackout](http://darkmatters.dk/blackout/)
          - Design and Production of [At Home with Hammershøi - Ordrupgaard Museum](http://darkmatters.dk/hammershoi/)
          
          **Tools and Technologies:** VDMX, MadMapper, Rhino3D, Processing, Arduino, Enttec DMX control, Artnet, Adobe PS IN IL AE 

      - layout: left
        border: weak
        title: ITU Intermedia Lab
        sub_title: Lab Manager
        caption: apr. 2014 - dec. 2014
        link: www.itu.dk
        quote: >
          Intermedia Lab provided a space for prototyping computational artefacts that are bigger than the laptop and the desk - a big space located on the ground floor of the IT University of Copenhagen that functions more as a laboratory than an auditorium.
        description: | # this will include new lines to allow paragraphs
          **About:** 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: right
        title: Royal Danish Academy - CITAstudio
        sub_title: MA in Architecture
        caption: 2017-2019
        quote: 
        description: | # this will include new lines to allow paragraphs
          Computation in Architecture is an international masters that explores the critical consideration of technology as a driver for thinking, forming and realising architecture. With specific focus on digital design, bio-materials and design, advanced modelling, smart sensing and robotic fabrication, the program fosters a dynamic, creative, intellectually rigorous and design-led environment that stimulates critical inquiry into issues of sustainability, site, structure, behavior, materiality and architectural expression.

      - layout: right
        title: Royal Danish Academy - Department 11
        sub_title: BA in Architecture
        caption: 2009-2013
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Description Bachelor 

#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.


#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Descrition of other stuff than strictly proffesional

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
